version: '2'
volumes:
    resin-data:
services:
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      - "USERNAME=balena"
      - "PASSWORD=balena"
      - "ENCRIPTION_KEY=balena"
    cap_add:
      - SYS_RAWIO
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/hci0:/dev/hci0"
    ports:
      - 80:80
